### ISSUE TITLE
composer失败

### ISSUE THREAD

**Issue by ZimoBoy** [Jiannei/laravel-response#11]
![image](https://user-images.githubusercontent.com/35425100/103206073-ffe19400-4935-11eb-8a11-36d0dd87db0a.png)

**Comment by ZimoBoy** [comment]
In response.php line 15:

  Class 'Jiannei\Enum\Laravel\Repositories\Enums\HttpStatusCodeEnum' not found


Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by Jiannei** [comment]
@ZimoBoy 感谢反馈。

目前依赖于 [jiannei/laravel-enum](https://github.com/Jiannei/laravel-enum)，可以先执行 `composer require jiannei/laravel-enum` 再执行 `composer require jiannei/laravel-response`
