### ISSUE TITLE
最新5.0版本对Format进行重写拓展无法使用

### ISSUE THREAD

**Issue by lisongkun** [jiannei/laravel-response#113]
按照已经关闭的issue,对Format进行重写扩展 并修改配置文件后无法正常访问

Target [Jiannei\Response\Laravel\Contracts\Format] is not instantiable while building [Jiannei\Response\Laravel\Response].

能力有限,翻看源码没找到原因,示例starter项目并未涉及到扩展Format,谢谢！

**Comment by lisongkun** [comment]
> ```
> <?php
> 
> namespace App\Support;
> 
> class ResponseFormat extends \Jiannei\Response\Laravel\Support\Format
> {
>   /**
>    * Format return data structure.
>    *
>    * @param  array|null  $data
>    * @param  string|null  $message
>    * @param  int  $code
>    * @param  null  $errors
>    * @return array
>    */
>   public function data(?array $data, ?string $message, int $code, $errors = null): array
>   {
>     return $this->formatDataFields([
>       'code' => $code,
>       'message' => $this->formatMessage($code, $message),
>       'data' => $data ?: (object) $data,
>       'error' => $errors ?: (object) [],
>       'status' => $this->formatStatus($code),
>       'timestamp' => (string) now()->getTimestampMs(),
>     ], $this->config);
>   }
> }
> 
> // config/response.php
> // Set the structure of the response data
>   'format' => [
>     // \Jiannei\Response\Laravel\Support\Format::class,
>     \App\Support\ResponseFormat::class,
>     [
>       'code' => ['alias' => 'code', 'show' => true],
>       'status' => ['alias' => 'status', 'show' => true],
>       'message' => ['alias' => 'message', 'show' => true],
>       //....
>       'error' => ['alias' => 'error', 'show' => false],
>       'timestamp' => ['alias' => 'timestamp', 'show' => true],
>     ],
> ```

一样的,我用的Laravel10的原因吗

**Comment by jiannei** [comment]
问题解决了吗 🤔

**Comment by lisongkun** [comment]
> 问题解决了吗 🤔

还没有呢,Laravel10 里不能用原先的解决方案,勉强用中间件替代
