### ISSUE TITLE
无法静态调用

### ISSUE THREAD

**Issue by Mr-wangwei** [jiannei/laravel-response#114]
Laravel： 11
php： 8.3
laravel-response：6

是文档没有更新吗？无法像文档里面一样使用静态方法调用
use Jiannei\Response\Laravel\Response;
<img width="712" alt="image" src="https://github.com/jiannei/laravel-response/assets/46190162/4320d42f-a1a7-4145-857b-aeafa41f920e">
<img width="966" alt="image" src="https://github.com/jiannei/laravel-response/assets/46190162/23ea7995-bc83-4c12-98b3-976a342560a4">
<img width="673" alt="image" src="https://github.com/jiannei/laravel-response/assets/46190162/49759de3-3b9c-4dad-aac3-874f69dc4b59">

**Comment by jiannei** [comment]
```php
use Jiannei\Response\Laravel\Support\Facades\Response;
```
