### ISSUE TITLE
新版本覆盖掉 bootstrap/app/php App\Exceptions\Handler::class 

### ISSUE THREAD

**Issue by LHongy** [jiannei/laravel-response#115]
6.0版本后，我改 App\Exceptions\Handler::class 的内容，没有任何反应，非常头疼。应该是哪里覆盖掉了这行代码？

$app->singleton(
    Illuminate\Contracts\Debug\ExceptionHandler::class,
    App\Exceptions\Handler::class
);

**Comment by jiannei** [comment]
6.0 版本不用引入异常 trait，Provider 中默认已经覆盖了框架异常响应

https://github.com/jiannei/laravel-response/blob/f713db7e83ef917965766dcadf679076600253e1/src/Providers/LaravelServiceProvider.php#L25-L28
