### ISSUE TITLE
安装报错，laravel 版本7.30.1

### ISSUE THREAD

**Issue by 2515104337** [Jiannei/laravel-response#12]
HP Fatal error:  Declaration of Jiannei\Enum\Laravel\Enum::castUsing(array $arguments) must be compatible with Illuminate\Contracts\Database\Eloquent\Castable::castUsing() in /home/vagrant/Code/new/vendor/jiannei/laravel-enum/src/Enum.php on line 26

In Enum.php line 26:
                                                                               
  Declaration of Jiannei\Enum\Laravel\Enum::castUsing(array $arguments) must   
  be compatible with Illuminate\Contracts\Database\Eloquent\Castable::castUsi  
  ng()                                                                         
                                                                               

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255

**Comment by Jiannei** [comment]
> HP Fatal error: Declaration of Jiannei\Enum\Laravel\Enum::castUsing(array $arguments) must be compatible with Illuminate\Contracts\Database\Eloquent\Castable::castUsing() in /home/vagrant/Code/new/vendor/jiannei/laravel-enum/src/Enum.php on line 26
> 
> In Enum.php line 26:
> 
> Declaration of Jiannei\Enum\Laravel\Enum::castUsing(array $arguments) must
> be compatible with Illuminate\Contracts\Database\Eloquent\Castable::castUsi
> ng()
> 
> Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255

感谢反馈。

这个问题是因为 laravel-enum 中适配了 laravel 8的model casts 特性，而没有对低版本进行兼容，可以尝试升级laravel 版本。

我考虑下怎样去兼容低版本🤔️

**Comment by Jiannei** [comment]
已移除对 laravel-enum 的依赖，支持独立使用
