### ISSUE TITLE
Is it really necessary to create app/exceptions/handler ?

### ISSUE THREAD

**Issue by uwla** [jiannei/laravel-response#121]
Thanks for the package!

The README setup provide instructions to create a file `app/Exceptions/Handler.php`:

```php
<?php

namespace App\Exceptions;

use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Jiannei\Response\Laravel\Support\Traits\ExceptionTrait;

class Handler extends ExceptionHandler
{
    use ExceptionTrait;
}
```

Is it really necessary? Because I noticed even if I do not create the file, the
package still seems to work when handling errors.

**Comment by jiannei** [comment]
Laravel 11 and above versions are no longer required :)
