### ISSUE TITLE
[Feature] Add config for fail http status

### ISSUE THREAD

**Issue by vanthao03596** [Jiannei/laravel-response#19]
Sometimes i want to return all fail response http status to 200 but keep error code in 'code' key.
It would be nice if we have have this.

**Comment by Jiannei** [comment]
Yes, this method was considered at the beginning. Almost all api responses of many projects return 200, but it is more ‘restful’ to return specific http status code  when an error occurs.

It is still worth considering, perhaps a good configuration item

**Comment by vanthao03596** [comment]
@Jiannei I think response.error_code should be null by default. 
If we set this value, we will return all fail() status to this value,
otherwise we return exact http status.
