### ISSUE TITLE
支持laravel5.5吗？

### ISSUE THREAD

**Issue by Ya-hui** [Jiannei/laravel-response#26]
支持laravel5.5吗？

**Comment by Jiannei** [comment]
@Ya-hui 支持 Laravel 7 以上版本

**Comment by Jiannei** [comment]
@Ya-hui   已支持 laravel 5.5 ~ laravel 8.x  

https://github.com/Jiannei/laravel-response/releases/tag/v4.0.0

**Comment by Ya-hui** [comment]
棒啊，太棒了，这个 可以自定义很多东西了
