### ISSUE TITLE
[建议]异常可以不暴露模型嘛

### ISSUE THREAD

**Issue by sym134** [Jiannei/laravel-response#27]
![image](https://user-images.githubusercontent.com/32946251/124681806-ee3c0300-defb-11eb-91d2-acbaa2d0c288.png)

**Comment by Jiannei** [comment]
@sym134 有没有好的方式

**Comment by Jiannei** [comment]
可以关注下 2.0 版本是否能满足需求 😎

**Comment by sym134** [comment]
> 可以关注下 2.0 版本是否能满足需求 😎

现在只看到是1.7嘛😔

**Comment by Jiannei** [comment]
> > 可以关注下 2.0 版本是否能满足需求 😎
> 
> 现在只看到是1.7嘛😔

已经在写文档了 😉

2.0 将支覆盖异常 message\code，就不会暴露 `\Symfony\Component\HttpKernel\Exception\NotFoundHttpException` 异常的默认提示了

**Comment by Jiannei** [comment]
新版本已支持 https://github.com/Jiannei/laravel-response/releases/tag/v4.0.0 👍
