### ISSUE TITLE
可以自定义显示分页参数吗？

### ISSUE THREAD

**Issue by sym134** [Jiannei/laravel-response#30]
api有些参数不需要，可以自定义吗

**Comment by Jiannei** [comment]
可以举个例子吗，比如自定义前是哪些参数，自定义后希望保留哪些参数

**Comment by sym134** [comment]
一般来说api 只要data、分页总数、当前页码就够了，当然也有部分可能需要每页行数，所以我想着应该可以自定义这部分，
我是目前写了个中间件解决了😄

**Comment by Jiannei** [comment]
> 一般来说api 只要data、分页总数、当前页码就够了，当然也有部分可能需要每页行数，所以我想着应该可以自定义这部分，
> 我是目前写了个中间件解决了😄

通过中间件把响应数据中的字段 unset 掉吗

**Comment by sym134** [comment]
> > 一般来说api 只要data、分页总数、当前页码就够了，当然也有部分可能需要每页行数，所以我想着应该可以自定义这部分，
> > 我是目前写了个中间件解决了😄
> 
> 通过中间件把响应数据中的字段 unset 掉吗

这个对于您这个组件应该比较好操作吧，我的想法是配置文件里面数组填入要保留的字段，然后响应数据那里判断保留，当然大佬有更好的办法也可以😄

**Comment by sym134** [comment]
> > 一般来说api 只要data、分页总数、当前页码就够了，当然也有部分可能需要每页行数，所以我想着应该可以自定义这部分，
> > 我是目前写了个中间件解决了😄
> 
> 通过中间件把响应数据中的字段 unset 掉吗

还有个情况，反馈一下，我看您的教程是不需要return的，但success和fail都需要return才行，

**Comment by Jiannei** [comment]
我也是这个想法，目前配置文件已经增加了饭回字段的配置

```
 // Set the structure of the response data
    'format' => [
        'fields' => [
            'status' => ['alias' => 'status', 'show' => true],
            'code' => ['alias' => 'code', 'show' => true],
            'message' => ['alias' => 'message', 'show' => true],
            'error' => ['alias' => 'error', 'show' => true],
            'data' => [
                'alias' => 'data',
                'show' => true,

                // When data is nested with data, such as returning paged data, you can also set an alias for the inner data
                'data' => [
                    'alias' => 'data', // data/rows/list
                ],
            ],
        ],
    ],
```

**Comment by sym134** [comment]
> 我也是这个想法，目前配置文件已经增加了返回字段的配置
> 
> ```
>  // Set the structure of the response data
>     'format' => [
>         'fields' => [
>             'status' => ['alias' => 'status', 'show' => true],
>             'code' => ['alias' => 'code', 'show' => true],
>             'message' => ['alias' => 'message', 'show' => true],
>             'error' => ['alias' => 'error', 'show' => true],
>             'data' => [
>                 'alias' => 'data',
>                 'show' => true,
> 
>                 // When data is nested with data, such as returning paged data, you can also set an alias for the inner data
>                 'data' => [
>                     'alias' => 'data', // data/rows/list
>                 ],
>             ],
>         ],
>     ],
> ```

帅气👍🏻

**Comment by Jiannei** [comment]
> 况，反馈一下，我看您的教程是不需要return的，但success和fail都需要return才行，

这个问题新开 issue ，提供下复现步骤。

**Comment by Jiannei** [comment]
已支持：https://github.com/Jiannei/laravel-response/releases/tag/v4.0.0 😎
