### ISSUE TITLE
No content 返回的不是JSON

### ISSUE THREAD

**Issue by winter-ice** [Jiannei/laravel-response#31]
No content 返回的不是JSON

**Comment by Jiannei** [comment]
204 状态码理论上不应该返回任何数据

**Comment by winter-ice** [comment]
那如果只想要message不想要data，应该用什么返回？

**Comment by Jiannei** [comment]
#30 是否和这个问题一样，希望能够自定义返回的参数吗？比如，只返回 message，data、code、error 都不需要？

**Comment by winter-ice** [comment]
也不完全一样吧，某些接口只需要返回一个提示信息。
现在的的方法第一个参数都是需要填入数据的，不得已就只能第一个参数写空数组，第二个参数写`message`。
只是需要能方便的返回一个`message` 并且成功的方法吧。
思考后觉得可能加入一个`ok`方法比较合适，不需要接受`data`参数，第一个参数就接受`message`。
考虑一下？

**Comment by winter-ice** [comment]
参考：https://github.com/f9webltd/laravel-api-response-helpers
提供了 success 和 ok 两个方法

**Comment by Jiannei** [comment]
> 也不完全一样吧，某些接口只需要返回一个提示信息。
> 现在的的方法第一个参数都是需要填入数据的，不得已就只能第一个参数写空数组，第二个参数写`message`。
> 只是需要能方便的返回一个`message` 并且成功的方法吧。
> 思考后觉得可能加入一个`ok`方法比较合适，不需要接受`data`参数，第一个参数就接受`message`。
> 考虑一下？

不错的建议

**Comment by Jiannei** [comment]
已支持：https://github.com/Jiannei/laravel-response/releases/tag/v4.0.0 😎
