### ISSUE TITLE
返回的是空数组，但是data返回的是对象

### ISSUE THREAD

**Issue by iWuxc** [Jiannei/laravel-response#60]
后台写：

return Response::success([]);

API返回：

{
    "status": "success",
    "code": 200,
    "message": "操作成功",
    "data": {},
    "error": {}
}

因为接口传的可能为空数组，期望返回格式：

{
    "status": "success",
    "code": 200,
    "message": "操作成功",
    "data": [],
    "error": {}
}

建议更改：'data' => $data ?: is_array($data) ? $data: (object) $data,

**Comment by Jiannei** [comment]
对于客户端而言，判断空数组 `[]` 和空对象`{}` 是不是一样的呢？

**Comment by iWuxc** [comment]
> 对于客户端而言，判断空数组 `[]` 和空对象`{}` 是不是一样的呢？

在和前端联调的时候，发现他们对数据类型有严格要求，所以出现在类型上校验不正确的场景，所以我不知道其他人在用您的插件出现过类似的问题没有

**Comment by Jiannei** [comment]
有对接过强类型语言的客户端，比如 android 和 iOS，返回结构中的 data 始终为对象类型。

```
{
    "status": "success",//  固定字符串类型
    "code": 200,// 固定整型
    "message": "操作成功",// 固定字符串类型
    "data": {},// 固定对象类型
    "error": {}// 固定对象类型
}
```

**Comment by iWuxc** [comment]
> 有对接过强类型语言的客户端，比如 android 和 iOS，返回结构中的 data 始终为对象类型。
> 
> ```
> {
>     "status": "success",//  固定字符串类型
>     "code": 200,// 固定整型
>     "message": "操作成功",// 固定字符串类型
>     "data": {},// 固定对象类型
>     "error": {}// 固定对象类型
> }
> ```

好的，谢谢
