### ISSUE TITLE
响应字段的格式化的处理建议

### ISSUE THREAD

**Issue by guanguans** [jiannei/laravel-response#77]
关于响应字段的格式化的处理，个人觉得不够灵活。建议配置成一个回调类型由使用者去处理。

我想了下大致改成这样：

## 配置

https://github.com/jiannei/laravel-response/blob/main/config/response.php#L54

```php
...
'format' => '`callable`'
...
```

## 格式化方法

https://github.com/jiannei/laravel-response/blob/main/src/Support/Traits/JsonResponseTrait.php#L241

```php

    /**
     * Format response data fields.
     *
     * @param  array  $responseData
     * @return array
     */
    protected function formatDataFields(array $responseData): array
    {
        
        if (is_null($format = Config::get('response.format'))) {
            return $responseData;
        }
      
        // 处理回调(不太健全)
        return app()->call($format, [
             'responseData' => $responseData,
             'request' => request(),
       ]);
    }
```

**Comment by jiannei** [comment]
不错的建议

**Comment by jiannei** [comment]
`config/response.php`中的`format`项现在支持配置成实现了`\Jiannei\Response\Laravel\Contracts\Format`的类，可以参考用例中的场景 [Jiannei\Response\Laravel\Tests\Support](https://github.com/jiannei/laravel-response/blob/eeafc6a862b95761bbfbce385460865576775b81/tests/Support/Format.php)

**Comment by guanguans** [comment]
谢谢更改。这样更改由接口交给用户区处理应该会灵活很多了。

[https://github.com/jiannei/laravel-response/blob/eeafc6a862b95761bbfbce385460865576775b81/src/Support/Format.php#L46](https://github.com/jiannei/laravel-response/blob/eeafc6a862b95761bbfbce385460865576775b81/src/Support/Format.php#L46)

这块儿的配置依赖似乎还没有消除。

**Comment by guanguans** [comment]
我想的是，现在用接口取代 `响应字段的格式化` 配置，那配置中如果再有这个配置，就好像已经是多余的了吧。这个配置应该交给接口类去控制。配置中应该加一下配置该接口类。这样使用者就可以自定义自己的格式化类了。

**Comment by jiannei** [comment]
如果自定义实现 Format，`config/response.php`中的 format 项应该类似于` 'format' => \App\Support\Format::class,`

**Comment by guanguans** [comment]
> 如果自定义实现 Format，`config/response.php`中的 format 项应该类似于` 'format' => \App\Support\Format::class,`

对我想的是这样的。

**Comment by jiannei** [comment]
稍作了调整，可以再关注下

**Comment by guanguans** [comment]
@jiannei 感谢做出的调整，有一点点我觉得还需要优化的地方，我稍后修改一下。pr 过来，麻烦你在看一下。

**Comment by jiannei** [comment]
> @jiannei 感谢做出的调整，有一点点我觉得还需要优化的地方，我稍后修改一下。pr 过来，麻烦你在看一下。

欢迎 pr  :sparkles:

**Comment by jiannei** [comment]
> @jiannei 感谢做出的调整，有一点点我觉得还需要优化的地方，我稍后修改一下。pr 过来，麻烦你在看一下。

欢迎 pr 👏
