### ISSUE TITLE
可否增加自定义公共字段返回，比如说request_id 或者time 之类的？

### ISSUE THREAD

**Issue by lotussha** [jiannei/laravel-response#78]
可否增加自定义公共字段返回，比如说request_id 或者time 之类的？

_Originally posted by @lotussha in https://github.com/jiannei/laravel-response/issues/57#issuecomment-1303211539_

**Comment by jiannei** [comment]
这种放在中间件去实现会不会好一点，因为提到的 request_id 或 time 字段都包含了业务逻辑

**Comment by lotussha** [comment]
请问下有大概的扩展思路吗？

**Comment by jiannei** [comment]
可参考 [FormatTest](https://github.com/jiannei/laravel-response/blob/eeafc6a862b95761bbfbce385460865576775b81/tests/FormatTest.php) 中的实现，在 `config/response.php` 中配置format为` \Jiannei\Response\Laravel\Tests\Support\Format::class`，这里的 Format 可以扩展基础类来自行扩展。

**Comment by lotussha** [comment]
> 

感谢！
